[package]
name = "analyze_polars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = { version="0.20.0", features=["lazy", "ndarray", "rows", "lazy_regex", "horizontal_concat"]}
serde_json = "1.0"
clap = { version = "3.1.12", features = ["derive"] }
