on:
  workflow_dispatch:

name: CI

jobs:
  build:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Display structure of downloaded files
        run: ls -R
      - uses: actions/download-artifact@v3
        with:
          name: analyze_polars
          path: target/release/analyze_polars
